// <auto-generated />
using System;
using Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Context.Migrations
{
    [DbContext(typeof(SolutionContext))]
    [Migration("20200514172013_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Corretoras.Corretora", b =>
                {
                    b.Property<int>("CorretoraId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Bairro")
                        .HasMaxLength(150);

                    b.Property<string>("Cidade")
                        .HasMaxLength(150);

                    b.Property<string>("CnpjCpf")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("Complemento")
                        .HasMaxLength(150);

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("EnderecoCorretor")
                        .HasMaxLength(150);

                    b.Property<string>("Estado")
                        .HasMaxLength(2);

                    b.Property<string>("MeioComunicacao")
                        .HasMaxLength(150);

                    b.Property<DateTime>("ModifieldDate");

                    b.Property<string>("RazaoSocialCorretor")
                        .HasMaxLength(150);

                    b.Property<string>("TipoMeioComunicacao")
                        .HasMaxLength(150);

                    b.Property<int>("UserID");

                    b.Property<int>("UserIDLastUpdate");

                    b.HasKey("CorretoraId");

                    b.ToTable("CUS_Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
